#!/bin/sh
echo ""
echo ""
echo "**********************************"
echo "*      ExtraChannelSelction         *"
echo "*           Kitte888             *"
echo "*                                *"
echo "**********************************"
echo ""
echo "Plugin successfully installed"
echo ""
echo ""
echo "You should restart GUI after ..."
echo ""
echo ""
sleep 5
exit 0
